# Generated by Django 3.1.4 on 2020-12-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scrape_gender', models.CharField(default='M/F', max_length=50)),
                ('Scrape_age', models.CharField(default='100', max_length=50)),
                ('Scrape_weight', models.CharField(default='weight class', max_length=200)),
                ('Scrape_height', models.CharField(default="9'0", max_length=50)),
                ('Scrape_pid', models.CharField(default='zzzzzzz', max_length=50)),
                ('Scrape_url', models.CharField(default='www.www.www', max_length=500)),
            ],
        ),
    ]
