# Generated by Django 3.1.4 on 2020-12-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='Scrape_date',
            field=models.CharField(default='00000000', max_length=500),
        ),
    ]
