# Generated by Django 3.1.4 on 2020-12-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_scrape_scrape_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='Scrape_len',
            field=models.CharField(default='(##) Years (##) Months', max_length=500),
        ),
    ]
