# Generated by Django 3.1.4 on 2020-12-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_scrape_scrape_len'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='Scrape_coms',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='Scrape_age',
            field=models.CharField(default='####', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='Scrape_height',
            field=models.CharField(default="#'#", max_length=50),
        ),
    ]
