# Generated by Django 3.1.4 on 2020-12-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201214_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='Scrape_abstime',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
